# Generated by Django 3.0.5 on 2020-04-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('company_name', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('industry', models.TextField(null=True)),
                ('date_created', models.DateField(null=True)),
            ],
        ),
    ]
