# Generated by Django 3.0.5 on 2020-04-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
