# Generated by Django 3.0.5 on 2020-04-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20200411_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('archive', 'archive')], default='archive', max_length=10),
        ),
    ]
