# Generated by Django 3.0.5 on 2020-04-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('archive', 'archive')], default='active', max_length=10),
        ),
    ]
