# Generated by Django 3.0.5 on 2020-04-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contract',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='site',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=20, null=True),
        ),
    ]
